version: '3.1'

services:
  library-app:
    build:
      context: .
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - library-db

  library-db:
    image: mysql:5.7
    restart: always
    container_name: library-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "library_db"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "root"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    depends_on:
      - keycloak

  keycloak-db:
    image: mysql:5.7
    restart: always
    container_name: keycloak-db
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: "keycloak_db"
      MYSQL_USER: ${DB_KEYCLOAK_USERNAME}
      MYSQL_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      MYSQL_ROOT_PASSWORD: "root"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  keycloak:
    image: jboss/keycloak
    restart: always
    container_name: keycloak
    environment:
      DB_VENDOR: "MYSQL"
      DB_ADDR: keycloak-db
      DB_DATABASE: "keycloak_db"
      DB_USER: ${DB_KEYCLOAK_USERNAME}
      DB_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    ports:
      - "8082:8080"
    depends_on:
      - keycloak-db

  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - library-db


  client:
    build:
      context: ./client
    restart: always
    ports:
      - "8081:80"