version: '3.1'

services:
  library-db:
    image: mysql:5.7
    restart: always
    container_name: library-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "dev_library_db"
      MYSQL_USER: "bestuser"
      MYSQL_PASSWORD: "bestuser"
      MYSQL_ROOT_PASSWORD: "root"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    depends_on:
      - keycloak-db

  keycloak-db:
    image: mysql:5.7
    restart: always
    container_name: keycloak-db
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: "dev_keycloak_db"
      MYSQL_USER: "keycloak"
      MYSQL_PASSWORD: "keycloak"
      MYSQL_ROOT_PASSWORD: "root"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: "MYSQL"
      DB_ADDR: keycloak-db
      DB_DATABASE: "dev_keycloak_db"
      DB_USER: "keycloak"
      DB_PASSWORD: "keycloak"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    ports:
      - "8082:8080"
    depends_on:
      - keycloak-db
#    links:
#      - "keycloak-db:keycloak-db"