version: '3.1'

services:
  library-db:
    image: mysql:5.7
    restart: always
    container_name: library-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "dev_library_db"
      MYSQL_USER: "bestuser"
      MYSQL_PASSWORD: "bestuser"
      MYSQL_ROOT_PASSWORD: "root"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci